platform :ios, '8.0'

pod 'AFNetworking', '~> 2.5.4'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'Masonry', '~>0.6'
#pod 'MBProgressHUD', '~> 0.9.1'
#pod 'MJRefresh', '~> 1.4.7'
#pod 'RDVTabBarController', '~> 1.1.9'
pod 'SDWebImage', '~> 3.7.2'
pod 'UIImage+BlurredFrame', '~> 0.0.4'
#pod 'NYXImagesKit', '~> 2.3'
pod 'KMCGeigerCounter', '~> 0.2.2'
#pod 'pop', '~> 1.0.7'
#pod 'SSKeychain', '~> 1.2.3'
pod 'Mantle', '~> 2.0.2' 
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'FDFullscreenPopGesture', '1.1'
#pod 'IQKeyboardManager'
pod 'Toast', '~> 2.4'
pod 'AFMInfoBanner', '~> 1.1'
pod 'SVProgressHUD', '~> 1.1.3'
#pod 'DOPDropDownMenu', '~> 0.1.1'
pod 'MWPhotoBrowser', '~> 2.1.1'
#pod 'AMSmoothAlert', '~> 1.0'
pod 'YTKKeyValueStore', '~> 0.1.2'
#pod "DKNightVersion", "~> 0.8.1"
pod 'UMengAnalytics-NO-IDFA', '~> 3.5.16'
